import { parseDocx } from './parser.js';
import * as db from './db.js';
import { available, chooseQuestions, formOf, gradeSession, sessionGroups, summarize, detachBankSessions } from './logic.js';

const app = document.querySelector('#app');
const state = { page: 'home', banks: [], sessions: [], draft: null, preview: null, reviewFilter: 'all', reviewIndex: 0, practiceIndex: 0, selected: new Set(), form: 'all', includeWord: true, notice: '' };
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const allGroups = () => state.banks.flatMap(bank => bank.vignettes || []);
const pct = (a, n) => n ? `${Math.round(a / n * 100)}%` : '—';
const labelForm = form => ({ vignette: 'Vignette 題組', standalone: '獨立單題', unknown: '待確認' })[formOf({ form })];
function blocksHtml(blocks = []) { return blocks.map(block => block.type === 'table' ? `<div class="table-wrap"><table>${block.rows.map(row => `<tr>${row.map(cell => `<td>${esc(cell)}</td>`).join('')}</tr>`).join('')}</table></div>` : `<p>${esc(block.text)}</p>${(block.images || []).map(src => `<img class="doc-img" src="${src}" alt="題目附圖">`).join('')}`).join(''); }
function questionBlocks(question, field) { return question[`${field}Blocks`] || (question[field] || []).map(text => ({ type: 'p', text, images: [] })); }
function questionReady(question) { return question.ready !== false && !!question.correctKey && question.options.length >= 2; }
function nav() { return `<header><button class="brand" data-go="home"><span>AR</span> Arc Practice</button><nav>${[['library', '題庫'], ['setup', '開始練習'], ['stats', '統計']].map(([page, label]) => `<button data-go="${page}" class="${state.page === page ? 'active' : ''}">${label}</button>`).join('')}</nav><button class="icon-btn" data-go="backup" title="本機資料與備份">本機資料</button></header>`; }
function shell(body, wide = false) { app.innerHTML = `${nav()}<main class="${wide ? 'wide-main' : ''}">${state.notice ? `<div class="notice">${esc(state.notice)}</div>` : ''}${body}</main>`; bind(); setIndeterminate(); }
function formCounts(groups) { return { v: groups.filter(g => formOf(g) === 'vignette').length, s: groups.filter(g => formOf(g) === 'standalone').reduce((n, g) => n + g.questions.length, 0), u: groups.filter(g => formOf(g) === 'unknown').length }; }
function home() { const groups = allGroups(), questions = groups.reduce((n, g) => n + g.questions.length, 0), count = formCounts(groups); shell(`<section class="hero"><div><div class="eyebrow">LOCAL-FIRST · PRIVATE BY DESIGN</div><h1>專注練習，<br><em>真正掌握。</em></h1><p>你的 CFA 題庫、進度與洞察，都只留在這台電腦。</p><div class="actions">${state.draft ? '<button class="primary" data-resume>繼續未完成練習 <b>→</b></button>' : '<button class="primary" data-go="setup">開始一回練習 <b>→</b></button>'}<button class="secondary" data-go="library">匯入 Word 題庫</button></div></div><div class="orb"><span>${questions}</span><small>QUESTIONS<br>READY</small></div></section><section class="metric-grid"><article><small>題庫形式</small><strong>${count.v} + ${count.s}</strong><p>${count.v} 題組、${count.s} 獨立單題${count.u ? `、${count.u} 待確認` : ''}</p></article><article><small>已完成練習</small><strong>${state.sessions.filter(s => s.submittedAt && s.source !== 'word').length}</strong><p>每次紀錄獨立保存</p></article><article><small>本機保存</small><strong>100%</strong><p>無需帳號或 AI API</p></article></section>`); }
function library() { if (state.preview) return preview(); const banks = state.banks.map((bank, bi) => { const c = formCounts(bank.vignettes); return `<article class="bank bank-manage"><div><small>${new Date(bank.importedAt).toLocaleDateString()}</small><h3>${esc(bank.name)}</h3><p>${c.v} 個 Vignette · ${c.s} 個獨立單題 · ${c.u} 個待確認 · ${bank.vignettes.reduce((n, g) => n + g.questions.length, 0)} 題</p></div><button class="danger" data-delete-bank="${bank.id}">移除</button><details><summary>檢視及更正題目形式</summary>${bank.vignettes.map((group, gi) => groupEditor(group, bi, gi, false)).join('')}</details></article>`; }).join(''); shell(`<div class="page-head"><div><div class="eyebrow">QUESTION BANK</div><h2>題庫管理</h2><p>Word 會辨識共用情境與獨立單題；不確定或答案衝突的內容不會進入練習。</p></div><label class="upload primary">選擇 Word 檔<input id="docx" type="file" accept=".docx"></label></div>${banks || '<div class="empty"><b>⌁</b><h3>尚未匯入題庫</h3><p>匯入 Word 題庫開始。</p></div>'}`); }
function groupEditor(group, bank, index, editing = true) { return `<div class="group-editor"><div><b>${esc(group.module)}</b><small>${group.questions.length} 題 · ${esc(group.formReason || '舊題庫沒有形式資料')}</small></div><label>形式<select data-form-group="${index}" ${editing ? '' : `data-bank="${bank}"`}><option value="unknown" ${formOf(group) === 'unknown' ? 'selected' : ''}>待確認</option><option value="vignette" ${formOf(group) === 'vignette' ? 'selected' : ''}>Vignette 題組</option><option value="standalone" ${formOf(group) === 'standalone' ? 'selected' : ''}>獨立單題</option></select></label></div>`; }
function preview() {
  const bank = state.preview, groups = bank.vignettes, allQuestions = groups.flatMap(group => group.questions);
  const count = formCounts(groups), warningCount = groups.flatMap(group => group.warnings.concat(group.questions.flatMap(q => q.warnings))).length;
  const exclusions = bank.exclusions || [];
  shell(`<div class="page-head"><div><div class="eyebrow">IMPORT PREVIEW</div><h2>逐題確認後匯入</h2><p>${count.v} 個 Vignette 題組 · ${count.s} 個獨立單題 · 共 ${allQuestions.length} 題 · ${warningCount} 個待確認</p></div><div class="actions"><button class="secondary" data-cancel-preview>取消</button><button class="primary" data-confirm-import>確認匯入</button></div></div>
  <p class="privacy-note">請核對預覽後匯入；缺少答案或有選項衝突的題目不會進入練習。</p>
  ${bank.warnings.map(w => `<div class="warning">${esc(w)}</div>`).join('')}
  <details class="preview exclusions" ${exclusions.length ? 'open' : ''}><summary><span>排除內容</span><b>${exclusions.length} 項</b></summary>${exclusions.length ? `<ul>${exclusions.map(item => `<li><b>${esc(item.reason)}</b><br>${esc(item.content)}</li>`).join('')}</ul>` : '<p class="muted">沒有排除項目。</p>'}</details>
  ${groups.map((group, i) => `<details class="preview" ${i === 0 ? 'open' : ''}><summary><span>${labelForm(group.form)} · ${esc(group.topic)}</span><b>${group.questions.length} 題</b></summary>${groupEditor(group, 0, i)}<div class="edit-grid"><label>Topic<input data-v="${i}" data-field="topic" value="${esc(group.topic)}"></label><label>Module<input data-v="${i}" data-field="module" value="${esc(group.module)}"></label></div>${group.context.length ? `<h4>共用情境（完整原文）</h4><div class="context-full">${blocksHtml(group.context)}</div>` : '<p class="muted">未偵測到共用情境。</p>'}${group.warnings.map(w => `<div class="warning">${esc(w)}</div>`).join('')}<div class="question-previews">${group.questions.map((q, qi) => `<article class="question-preview ${questionReady(q) ? '' : 'unreliable'}"><h4>${esc(q.header || `題目 ${qi + 1}`)} ${questionReady(q) ? '' : '<mark>不可練習</mark>'}</h4><div class="original-content">${blocksHtml(questionBlocks(q, 'stem'))}</div><ol class="preview-options" type="A">${q.options.map(option => `<li>${esc(option.text.replace(/^[A-Z][.)]\s*/, ''))}</li>`).join('')}</ol><div class="answer-edit"><label>正確答案<select data-answer="${i}|${qi}"><option value="">待確認</option>${q.options.map(option => `<option value="${option.key}" ${q.correctKey === option.key ? 'selected' : ''}>${option.key}</option>`).join('')}</select></label><div><small>Word 原作答（獨立匯入紀錄）</small><b>${esc(q.originalAnswerKey || q.originalAnswerRaw || '未提供')}</b></div></div><h5>官方詳解</h5><div class="original-content">${blocksHtml(questionBlocks(q, 'explanation')) || '<p class="muted">未辨識到詳解。</p>'}</div>${(q.optionConflicts || []).map(c => `<div class="warning">選項 ${esc(c.key)} 衝突：${c.values.map(esc).join(' / ')}</div>`).join('')}${q.warnings.map(w => `<div class="warning">${esc(w)}</div>`).join('')}</article>`).join('')}</div></details>`).join('')}`);
}
function topicData(groups) { return [...new Set(groups.map(g => g.topic))].map(topic => ({ topic, groups: groups.filter(g => g.topic === topic) })); }
function scopeState(groups, topic, module) { const keys = groups.filter(g => g.topic === topic && (!module || g.module === module)); return keys.length && keys.every(g => state.selected.has(`t:${topic}`) || state.selected.has(`m:${topic}|${g.module}`) || state.selected.has('all')); }
function setup() { const groups = allGroups(); if (!groups.length) { shell('<div class="empty"><h2>先匯入題庫</h2><p>需要至少一個可用題目才能開始。</p><button class="primary" data-go="library">前往匯入</button></div>'); return; } const scoped = available(groups, state.selected, state.form), count = formCounts(scoped); shell(`<div class="page-head"><div><div class="eyebrow">BUILD A SESSION</div><h2>這次想練什麼？</h2></div></div><section class="form-filter panel"><h3>01 題目形式</h3>${[['all', '全部'], ['vignette', 'Vignette 題組'], ['standalone', '獨立單題']].map(([value, label]) => `<label><input type="radio" name="form" value="${value}" ${state.form === value ? 'checked' : ''}>${label}</label>`).join('')}<p>待確認項目不會進入練習，請先在題庫管理更正。</p></section><div class="setup-grid"><section class="panel"><h3>02 選擇 Topic／Module</h3><label class="select-all"><input type="checkbox" data-all ${state.selected.has('all') ? 'checked' : ''}><b>全部主題</b><small>${groups.reduce((n, g) => n + g.questions.length, 0)} 題</small></label>${topicData(groups).map(({ topic, groups: topicGroups }) => { const modules = [...new Set(topicGroups.map(g => g.module))]; const qn = topicGroups.reduce((n, g) => n + g.questions.length, 0); return `<details class="topic"><summary><label><input type="checkbox" data-topic="${esc(topic)}" ${scopeState(groups, topic) ? 'checked' : ''}><b>${esc(topic)}</b><small>${qn} 題 · ${scopeState(groups, topic) ? '已選' : '未全選'}</small></label></summary><div class="modules">${modules.map(module => { const mg = topicGroups.filter(g => g.module === module); return `<label><input type="checkbox" data-module="${esc(topic)}|${esc(module)}" ${scopeState(groups, topic, module) ? 'checked' : ''}>${esc(module)} <small>${mg.reduce((n, g) => n + g.questions.length, 0)} 題</small></label>`; }).join('')}</div></details>`; }).join('')}</section><section class="panel"><h3>03 設定抽題</h3><label>抽題方式<select id="mode"><option value="random">隨機</option><option value="unseen">優先未做</option><option value="wrong">只練錯題</option></select></label><label>計算方式<select id="count-by"><option value="questions">依題數</option><option value="units">依題組／獨立題數</option></select></label><label>目標數量<input id="amount" type="number" min="1" value="1"></label><div class="availability"><strong>${count.v}</strong> 個 Vignette 題組 · <strong>${count.s}</strong> 個獨立單題 · <strong>${scoped.reduce((n, g) => n + g.questions.length, 0)}</strong> 題可用</div><button class="primary wide" data-plan ${scoped.length ? '' : 'disabled'}>預覽本次練習 →</button></section></div>`); }
function setIndeterminate() { if (state.page !== 'setup') return; const groups = allGroups(), selectedGroups = groups.filter(g => state.selected.has('all') || state.selected.has(`t:${g.topic}`) || state.selected.has(`m:${g.topic}|${g.module}`)); const all = document.querySelector('[data-all]'); if (all) all.indeterminate = selectedGroups.length > 0 && selectedGroups.length < groups.length; document.querySelectorAll('[data-topic]').forEach(input => { const gs = groups.filter(g => g.topic === input.dataset.topic), n = gs.filter(g => state.selected.has('all') || state.selected.has(`t:${g.topic}`) || state.selected.has(`m:${g.topic}|${g.module}`)).length; input.indeterminate = n > 0 && n < gs.length; }); }
function planSession() { const pool = available(allGroups(), state.selected, state.form), picked = chooseQuestions(pool, document.querySelector('#mode').value, Math.max(1, +document.querySelector('#amount').value || 1), state.sessions, Math.random, document.querySelector('#count-by').value); if (!picked.length) { state.notice = '此條件沒有可用題目。'; return render(); } const vignetteCount = picked.filter(u => formOf(u.group) === 'vignette').length, standaloneCount = picked.filter(u => formOf(u.group) === 'standalone').length, total = picked.reduce((n, u) => n + u.questions.length, 0); if (confirm(`本次包含 ${vignetteCount} 個完整 Vignette 題組、${standaloneCount} 個獨立單題，共 ${total} 題。開始練習？`)) { const draft = { id: `session_${Date.now()}`, createdAt: new Date().toISOString(), units: picked.map(u => ({ groupId: u.group.id, questionIds: u.questions.map(q => q.id) })), responses: {} }; state.draft = draft; state.sessions.push(draft); db.put('sessions', draft); state.practiceIndex = 0; state.page = 'practice'; render(); } }
function currentSession() { const session = state.draft || state.sessions.find(s => !s.submittedAt); if (session) state.draft = session; return session; }
function practice() { const session = currentSession(); if (!session) { state.page = 'setup'; return render(); } const groups = sessionGroups(session, allGroups()), items = groups.flatMap(group => group.questions.map(question => ({ question, group }))), item = items[state.practiceIndex]; if (!item) { state.draft = null; state.page = 'setup'; state.notice = '此練習的題庫已移除，請重新開始。'; return render(); } const response = session.responses[item.question.id] || {}, vignette = formOf(item.group) === 'vignette'; shell(`<div class="practice-top"><div class="save-zone"><button class="secondary" data-save-exit>← 儲存並離開</button></div><div class="progress-zone"><b>題目 ${state.practiceIndex + 1} / ${items.length}</b><div class="progress"><i style="width:${(state.practiceIndex + 1) / items.length * 100}%"></i></div></div><div class="submit-zone"><button class="primary" data-submit>Submit</button></div></div><div class="practice-layout ${vignette ? '' : 'standalone-layout'}">${vignette ? `<aside><div class="eyebrow">VIGNETTE</div><h3>${esc(item.group.module)}</h3><div class="vignette">${blocksHtml(item.group.context)}</div></aside>` : ''}<section class="question"><div class="q-meta"><span>${vignette ? 'VIGNETTE QUESTION' : '獨立單題'} ${state.practiceIndex + 1}</span><button data-flag class="flag ${response.flagged ? 'on' : ''}">⚑ 待確認</button></div><h2>${blocksHtml(questionBlocks(item.question, 'stem'))}</h2><div class="options">${item.question.options.map(option => `<label class="option ${response.selected === option.key ? 'chosen' : ''}"><input type="radio" name="answer" value="${option.key}" ${response.selected === option.key ? 'checked' : ''}><b>${option.key}</b><span>${esc(option.text.replace(/^[A-Z][.)]\s*/, ''))}</span></label>`).join('')}</div><div class="confidence"><span>信心程度（選填）</span>${[['sure', '確定'], ['unsure', '不確定'], ['guess', '猜的']].map(([key, label]) => `<button data-confidence="${key}" class="${response.confidence === key ? 'on' : ''}">${label}</button>`).join('')}</div><div class="question-nav"><button class="secondary" data-prev ${state.practiceIndex === 0 ? 'disabled' : ''}>← 上一題</button><button class="primary" data-next>${state.practiceIndex === items.length - 1 ? '回到第一題' : '下一題 →'}</button></div></section></div>`, true); }
async function persistDraft() { if (state.draft) await db.put('sessions', state.draft); }
function submit() { const groups = sessionGroups(state.draft, allGroups()), total = groups.reduce((n, g) => n + g.questions.length, 0), answered = Object.values(state.draft.responses).filter(r => r.selected).length; if (answered < total && !confirm(`還有 ${total - answered} 題未作答。仍要直接提交嗎？`)) return; const graded = gradeSession(state.draft, groups); state.sessions = state.sessions.map(s => s.id === graded.id ? graded : s); state.draft = null; db.put('sessions', graded); state.reviewId = graded.id; state.page = 'result'; render(); }
function result() { const session = state.sessions.find(s => s.id === state.reviewId) || state.sessions.filter(s => s.submittedAt).at(-1); if (!session) { state.page = 'home'; return render(); } const groups = sessionGroups(session, allGroups()), map = new Map(groups.flatMap(group => group.questions.map(question => [question.id, { question, group }]))), correct = session.answers.filter(a => a.correct).length, total = session.answers.length; const rows = session.answers.filter(a => state.reviewFilter === 'all' || state.reviewFilter === 'wrong' && !a.correct || state.reviewFilter === 'sureWrong' && !a.correct && a.confidence === 'sure' || state.reviewFilter === 'guessRight' && a.correct && a.confidence === 'guess'), answer = rows[Math.min(state.reviewIndex, Math.max(0, rows.length - 1))], item = answer && map.get(answer.questionId), vignette = item && formOf(item.group) === 'vignette'; shell(`<section class="result-hero"><div><div class="eyebrow">SESSION COMPLETE</div><h2>${pct(correct, total)}</h2><p>${correct} / ${total} 題答對</p></div><div class="ring" style="--p:${total ? correct / total * 360 : 0}deg"><span>${correct}<small>正確</small></span></div></section><div class="filters">${[['all', '全部'], ['wrong', '只看錯題'], ['sureWrong', '確定但答錯'], ['guessRight', '猜對']].map(([key, label]) => `<button data-filter="${key}" class="${state.reviewFilter === key ? 'active' : ''}">${label}</button>`).join('')}</div>${item ? `<div class="review ${vignette ? '' : 'standalone-layout'}">${vignette ? `<aside><h3>完整 Vignette</h3>${blocksHtml(item.group.context)}</aside>` : ''}<section><div class="q-meta"><span>${vignette ? 'Vignette 題組' : '獨立單題'}</span><b class="${answer.correct ? 'good' : 'bad'}">${answer.correct ? '答對' : '答錯'}</b></div><h2>${blocksHtml(questionBlocks(item.question, 'stem'))}</h2><div class="options">${item.question.options.map(o => `<p><b>${esc(o.key)}.</b> ${esc(o.text.replace(/^[A-Z][.)]\s*/, ''))}</p>`).join('')}</div><div class="answer-compare"><div><small>你的答案</small><b>${esc(answer.selected || '未作答')}</b></div><div><small>正確答案</small><b>${esc(item.question.correctKey || item.question.answerRaw)}</b></div></div><h3>官方詳解</h3>${blocksHtml(questionBlocks(item.question, 'explanation')) || '<p>此題未辨識到詳解。</p>'}<div class="question-nav"><button class="secondary" data-review-prev>←</button><span>${state.reviewIndex + 1} / ${rows.length}</span><button class="secondary" data-review-next>→</button></div></section></div>` : '<div class="empty"><h3>此篩選沒有題目</h3></div>'}`, true); }
function statsRow(group, title) { return `<div class="stats-row"><b>${esc(title)}${group.vignetteCount ? `<small>${group.vignetteCount} 個題組</small>` : ''}</b><span>${pct(group.firstCorrect, group.firstN)}<small>${group.firstCorrect}/${group.firstN}</small></span><span>${pct(group.latestCorrect, group.latestN)}<small>${group.latestCorrect}/${group.latestN}</small></span><span>${group.practiced}/${group.total}</span><span>${group.repeatedWrong}</span><span>${pct(group.retryCorrect, group.retryN)}<small>${group.retryCorrect}/${group.retryN}</small></span></div>`; }
function stats() { const topics = summarize(state.sessions, allGroups(), state.includeWord); shell(`<div class="page-head"><div><div class="eyebrow">PERFORMANCE</div><h2>學習統計</h2><p>題數與正確率以個別題目計算；Vignette 題組數另行標示。</p><label class="word-toggle"><input type="checkbox" data-include-word ${state.includeWord ? 'checked' : ''}> 統計包含 Word 匯入紀錄</label></div></div><div class="stats-table"><div class="stats-row head"><b>範圍</b><span>首次正確率</span><span>最近正確率</span><span>題庫覆蓋</span><span>重複答錯</span><span>錯題重練</span></div>${topics.map(topic => `<details class="stat-topic"><summary>${statsRow(topic, topic.name)}</summary><div class="module-stats">${topic.modules.map(module => statsRow(module, module.name)).join('')}</div></details>`).join('')}</div><details class="method"><summary>統計如何計算？</summary><p><b>首次作答：</b>每個題目第一次提交。<b>最近一次：</b>每題最後一次提交。<b>覆蓋：</b>至少提交一次的不同題目／題庫總題目。<b>重複答錯：</b>至少答錯兩次的題目。所有比率均以個別題目計算。</p></details>`); }
function backup() { shell(`<div class="page-head"><div><div class="eyebrow">DATA & PRIVACY</div><h2>本機資料</h2><p>資料只保存在本工具專用的瀏覽器 IndexedDB，不會上傳。</p><p class="privacy-note">🔒 不會影響其他網站的資料。</p></div></div><div class="setup-grid"><section class="panel"><h3>換電腦使用</h3><p>下載 JSON 備份，在另一台電腦開啟本站並還原。</p><button class="primary" data-export>下載完整備份</button><label class="upload secondary">還原備份 JSON<input id="restore" type="file" accept="application/json,.json"></label></section><section class="panel danger-panel"><h3>清除全部測試資料</h3><p>清除題庫、Word 原作答匯入紀錄、網站作答紀錄、未完成練習及相關設定。此動作無法復原。</p><button class="danger" data-clear-all>清除全部測試資料</button></section></div>`); }
function render() { const notice = state.notice; state.notice = ''; ({ home, library, setup, practice, result, stats, backup }[state.page] || home)(); if (notice) { state.notice = notice; const main = document.querySelector('main'); main?.insertAdjacentHTML('afterbegin', `<div class="notice">${esc(notice)}</div>`); } }
function wordSessionFromBank(bank) {
  const answers = bank.vignettes.flatMap(group => group.questions.filter(q => questionReady(q) && q.originalAnswerKey && formOf(group) !== 'unknown').map(q => ({ questionId: q.id, selected: q.originalAnswerKey, correct: q.originalAnswerKey === q.correctKey, confidence: '', flagged: false, topic: group.topic, module: group.module })));
  return { id: `word_${bank.id}`, source: 'word', sourceLabel: 'Word 匯入紀錄', bankId: bank.id, createdAt: bank.importedAt, submittedAt: bank.importedAt, answers, responses: {} };
}
async function removeBank(bank) {
  const remaining = state.banks.filter(b => b.id !== bank.id);
  const changes = detachBankSessions(bank, remaining.flatMap(b => b.vignettes || []), state.sessions);
  await db.remove('banks', bank.id);
  for (const id of changes.removeIds) await db.remove('sessions', id);
  for (const session of changes.updates) await db.put('sessions', session);
  const removed = new Set(changes.removeIds), updated = new Map(changes.updates.map(s => [s.id, s]));
  state.banks = remaining;
  state.sessions = state.sessions.filter(s => !removed.has(s.id)).map(s => updated.get(s.id) || s);
  state.draft = state.sessions.find(s => !s.submittedAt) || null;
  state.practiceIndex = 0;
}
function selectedQuestion() { return sessionGroups(state.draft, allGroups()).flatMap(g => g.questions)[state.practiceIndex]; }
function bind() {
  document.querySelectorAll('[data-go]').forEach(el => el.onclick = () => { state.page = el.dataset.go; render(); });
  document.querySelector('[data-resume]')?.addEventListener('click', () => { state.page = 'practice'; render(); });
  const file = document.querySelector('#docx'); if (file) file.onchange = async () => { try { state.preview = await parseDocx(file.files[0]); render(); } catch (error) { state.notice = error.message; render(); } };
  document.querySelectorAll('[data-answer]').forEach(el => el.onchange = () => { const [gi, qi] = el.dataset.answer.split('|').map(Number), question = state.preview.vignettes[gi].questions[qi]; question.correctKey = el.value; question.ready = !!el.value && question.options.length >= 2 && !question.warnings.some(w => w.startsWith('選項 ')); render(); });
  document.querySelectorAll('[data-field]').forEach(el => el.oninput = () => state.preview.vignettes[+el.dataset.v][el.dataset.field] = el.value);
  document.querySelectorAll('[data-form-group]').forEach(el => el.onchange = async () => { const bankIndex = el.dataset.bank; const bank = bankIndex === undefined ? state.preview : state.banks[+bankIndex]; const group = bank.vignettes[+el.dataset.formGroup]; group.form = el.value; group.formReason = '使用者手動確認'; if (bankIndex !== undefined) await db.put('banks', bank); render(); });
  document.querySelector('[data-cancel-preview]')?.addEventListener('click', () => { state.preview = null; render(); });
  document.querySelector('[data-confirm-import]')?.addEventListener('click', async () => {
    const bank = state.preview, duplicate = state.banks.find(b => b.contentId === bank.contentId || b.id === bank.id);
    if (duplicate && !confirm('同一份 Word 已匯入。取代題庫並刪除該題庫的測試作答紀錄？')) return;
    if (duplicate) await removeBank(duplicate);
    await db.put('banks', bank); state.banks.push(bank);
    const session = wordSessionFromBank(bank);
    if (session.answers.length) { await db.put('sessions', session); state.sessions.push(session); }
    state.preview = null; render();
  });
  document.querySelectorAll('[data-delete-bank]').forEach(el => el.onclick = async () => {
    const bank = state.banks.find(b => b.id === el.dataset.deleteBank);
    if (!bank || !confirm('移除這份題庫及其作答紀錄？')) return;
    await removeBank(bank); render();
  });
  document.querySelectorAll('input[name=form]').forEach(el => el.onchange = () => { state.form = el.value; render(); });
  document.querySelector('[data-all]')?.addEventListener('change', el => { state.selected.clear(); if (el.target.checked) state.selected.add('all'); render(); });
  document.querySelectorAll('[data-topic]').forEach(el => el.onchange = () => { state.selected.delete('all'); const key = `t:${el.dataset.topic}`; [...state.selected].filter(x => x.startsWith(`m:${el.dataset.topic}|`)).forEach(x => state.selected.delete(x)); if (el.checked) state.selected.add(key); else state.selected.delete(key); render(); });
  document.querySelectorAll('[data-module]').forEach(el => el.onchange = () => { state.selected.delete('all'); const [topic] = el.dataset.module.split('|'), topicKey = `t:${topic}`; if (state.selected.delete(topicKey)) [...new Set(allGroups().filter(g => g.topic === topic).map(g => g.module))].filter(m => m !== el.dataset.module.slice(topic.length + 1)).forEach(m => state.selected.add(`m:${topic}|${m}`)); const key = `m:${el.dataset.module}`; if (el.checked) state.selected.add(key); else state.selected.delete(key); render(); });
  document.querySelector('[data-plan]')?.addEventListener('click', planSession);
  document.querySelectorAll('input[name=answer]').forEach(el => el.onchange = () => { const q = selectedQuestion(); state.draft.responses[q.id] = { ...(state.draft.responses[q.id] || {}), selected: el.value }; persistDraft(); render(); });
  document.querySelectorAll('[data-confidence]').forEach(el => el.onclick = () => { const q = selectedQuestion(); state.draft.responses[q.id] = { ...(state.draft.responses[q.id] || {}), confidence: el.dataset.confidence }; persistDraft(); render(); });
  document.querySelector('[data-flag]')?.addEventListener('click', () => { const q = selectedQuestion(), r = state.draft.responses[q.id] || {}; state.draft.responses[q.id] = { ...r, flagged: !r.flagged }; persistDraft(); render(); });
  document.querySelector('[data-prev]')?.addEventListener('click', () => { state.practiceIndex--; render(); });
  document.querySelector('[data-next]')?.addEventListener('click', () => { const n = sessionGroups(state.draft, allGroups()).reduce((sum, g) => sum + g.questions.length, 0); state.practiceIndex = (state.practiceIndex + 1) % n; render(); });
  document.querySelector('[data-save-exit]')?.addEventListener('click', () => { persistDraft(); state.page = 'home'; render(); }); document.querySelector('[data-submit]')?.addEventListener('click', submit);
  document.querySelector('[data-include-word]')?.addEventListener('change', e => { state.includeWord = e.target.checked; render(); });
  document.querySelectorAll('[data-filter]').forEach(el => el.onclick = () => { state.reviewFilter = el.dataset.filter; state.reviewIndex = 0; render(); }); document.querySelector('[data-review-prev]')?.addEventListener('click', () => { state.reviewIndex = Math.max(0, state.reviewIndex - 1); render(); }); document.querySelector('[data-review-next]')?.addEventListener('click', () => { state.reviewIndex++; render(); });
  document.querySelector('[data-clear-all]')?.addEventListener('click', async () => { if (!confirm('確定清除本工具的全部題庫、作答紀錄、未完成練習及設定？此動作無法復原。')) return; await db.clearAll(); state.banks = []; state.sessions = []; state.draft = null; state.preview = null; state.reviewId = null; state.reviewIndex = 0; state.practiceIndex = 0; state.reviewFilter = 'all'; state.includeWord = true; state.selected.clear(); state.form = 'all'; state.notice = '本工具的全部測試資料已清除。'; state.page = 'home'; render(); });
  document.querySelector('[data-export]')?.addEventListener('click', async () => { const blob = new Blob([JSON.stringify(await db.exportData(), null, 2)], { type: 'application/json' }), a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `arc-cfa-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click(); URL.revokeObjectURL(a.href); });
  const restore = document.querySelector('#restore'); if (restore) restore.onchange = async () => { try { await db.importData(JSON.parse(await restore.files[0].text())); state.banks = await db.all('banks'); state.sessions = await db.all('sessions'); state.notice = '備份已還原'; state.page = 'home'; render(); } catch (error) { alert(error.message); } };
}
(async () => { state.banks = await db.all('banks'); state.sessions = await db.all('sessions'); state.draft = state.sessions.find(s => !s.submittedAt) || null; render(); })();
